<?php
declare(strict_types=1);

namespace BtcAccount;
require_once __DIR__ . '/Client.php';

/** A single authenticated encrypted state; the master key is never generated by PHP. */
final class Store
{
    private const AAD = 'BTC-monitor-account-state-v1';
    private const MAX_BYTES = 8388608;

    public function __construct(
        private string $directory = '/var/lib/btc-monitor-account',
        private string $keyFile = '/var/lib/btc-monitor-account-key/master.key',
    ) {
        if (!str_starts_with($directory, '/') || !str_starts_with($keyFile, '/')) self::failure();
        $webRoot = realpath(dirname(__DIR__, 2));
        foreach ([$directory, $keyFile] as $path) {
            if (str_contains($path, '/..') || str_contains($path, '/./') || is_link($path)) self::failure();
            $real = realpath($path) ?: $path;
            if ($webRoot && ($real === $webRoot || str_starts_with($real, $webRoot . '/'))) self::failure();
        }
        if (str_starts_with($keyFile, rtrim($directory, '/') . '/')) self::failure();
    }

    public function read(): array
    {
        return $this->locked(LOCK_SH, fn(): array => $this->readUnlocked());
    }

    /** Callback must return the complete replacement state. Never hold this across network I/O. */
    public function update(callable $update): array
    {
        return $this->locked(LOCK_EX, function () use ($update): array {
            $next = $update($this->readUnlocked());
            if (!is_array($next) || !is_string($next['generation'] ?? null) || !is_bool($next['connected'] ?? null)) self::failure();
            $this->writeUnlocked($next);
            return $next;
        });
    }

    /** One remote operation at a time, while disconnect remains immediately available. */
    public function exclusiveOperation(callable $operation): mixed
    {
        $handle = $this->openLock('operation.lock');
        if (!flock($handle, LOCK_EX | LOCK_NB)) {
            fclose($handle);
            throw new AccountException('operation_busy', '正在验证或同步账户，请稍后重试。', 5, 409);
        }
        try { return $operation(); }
        finally { flock($handle, LOCK_UN); fclose($handle); }
    }

    private function locked(int $mode, callable $operation): mixed
    {
        $handle = $this->openLock('state.lock');
        if (!flock($handle, $mode)) { fclose($handle); self::failure(); }
        try { return $operation(); }
        finally { flock($handle, LOCK_UN); fclose($handle); }
    }

    private function openLock(string $name)
    {
        if (!is_dir($this->directory) && !@mkdir($this->directory, 0700, true) && !is_dir($this->directory)) self::failure();
        if (is_link($this->directory) || !@chmod($this->directory, 0700)) self::failure();
        $file = $this->directory . '/' . $name;
        if (is_link($file)) self::failure();
        $handle = @fopen($file, 'c');
        if ($handle === false) self::failure();
        if (!@chmod($file, 0600)) { fclose($handle); self::failure(); }
        return $handle;
    }

    private function readUnlocked(): array
    {
        $file = $this->directory . '/state.enc.json';
        clearstatcache(true, $file);
        if (!file_exists($file)) return ['generation' => 'unconfigured', 'connected' => false, 'nextAllowedAt' => 0];
        if (is_link($file) || !is_file($file) || filesize($file) > self::MAX_BYTES || (fileperms($file) & 0077) !== 0) self::failure();
        $raw = @file_get_contents($file);
        if ($raw === false) self::failure();
        try {
            $envelope = json_decode($raw, true, 8, JSON_THROW_ON_ERROR);
            if (!is_array($envelope) || ($envelope['version'] ?? null) !== 1) self::failure();
            $iv = base64_decode($envelope['iv'] ?? '', true);
            $tag = base64_decode($envelope['tag'] ?? '', true);
            $ciphertext = base64_decode($envelope['ciphertext'] ?? '', true);
            if ($iv === false || strlen($iv) !== 12 || $tag === false || strlen($tag) !== 16 || $ciphertext === false) self::failure();
            $plain = openssl_decrypt($ciphertext, 'aes-256-gcm', $this->key(), OPENSSL_RAW_DATA, $iv, $tag, self::AAD);
            if ($plain === false) self::failure();
            $state = json_decode($plain, true, 64, JSON_THROW_ON_ERROR);
            if (!is_array($state) || !is_string($state['generation'] ?? null) || !is_bool($state['connected'] ?? null)) self::failure();
            return $state;
        } catch (\Throwable) { self::failure(); }
    }

    private function writeUnlocked(#[\SensitiveParameter] array $state): void
    {
        $temp = null;
        try {
            $iv = random_bytes(12); $tag = '';
            $plain = json_encode($state, JSON_THROW_ON_ERROR | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
            $ciphertext = openssl_encrypt($plain, 'aes-256-gcm', $this->key(), OPENSSL_RAW_DATA, $iv, $tag, self::AAD, 16);
            if ($ciphertext === false) self::failure();
            $envelope = json_encode(['version' => 1, 'iv' => base64_encode($iv), 'tag' => base64_encode($tag),
                'ciphertext' => base64_encode($ciphertext)], JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);
            if (strlen($envelope) > self::MAX_BYTES) self::failure();
            $temp = $this->directory . '/.state-' . bin2hex(random_bytes(16));
            $oldMask = umask(0077);
            try { $handle = @fopen($temp, 'x'); } finally { umask($oldMask); }
            if ($handle === false) self::failure();
            try {
                if (!@chmod($temp, 0600) || fwrite($handle, $envelope) !== strlen($envelope) || !fflush($handle)
                    || (function_exists('fsync') && !fsync($handle))) self::failure();
            } finally { fclose($handle); }
            if (!@rename($temp, $this->directory . '/state.enc.json')) self::failure();
        } catch (\Throwable) { self::failure(); }
        finally { if ($temp !== null && is_file($temp)) @unlink($temp); }
    }

    private function key(): string
    {
        clearstatcache(true, $this->keyFile);
        if (is_link($this->keyFile) || !is_file($this->keyFile) || (fileperms($this->keyFile) & 0137) !== 0) self::failure();
        $key = @file_get_contents($this->keyFile);
        if ($key === false || strlen($key) !== 32) self::failure();
        return $key;
    }

    private static function failure(): never
    {
        throw new AccountException('storage_unavailable', '账户私密存储暂时不可用，请检查本地服务状态。原有数据未被重置。', 60, 503);
    }
}
