// Rebuild the hand-authored catalog with Node.js; no package installation required.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const directory = path.dirname(fileURLToPath(import.meta.url));
const names = ['shell','plugins','admin','user','tips','common','review'];
const normalize = value => value.replace(/\s+/g, ' ').trim();
const messages = {}, patterns = [];
for (const name of names) {
    const file = path.join(directory, 'zh-CN', name + '.json');
    if (fs.existsSync(file)) {
        for (const [source, translated] of Object.entries(JSON.parse(fs.readFileSync(file, 'utf8')))) {
            const key = normalize(source);
            if (!key || typeof translated !== 'string' || !translated.trim()) throw new Error('Empty message: ' + file);
            if (/\ufffd/.test(source + translated)) throw new Error('Invalid encoding: ' + key);
            if (messages[key] && messages[key] !== translated) throw new Error('Conflicting translation: ' + key);
            messages[key] = translated;
        }
    }
    const patternFile = path.join(directory, 'zh-CN', name + '-patterns.json');
    if (fs.existsSync(patternFile)) {
        for (const item of JSON.parse(fs.readFileSync(patternFile, 'utf8'))) {
            if (!item.pattern.startsWith('^') || !item.pattern.endsWith('$')) throw new Error('Patterns must match a whole message: ' + patternFile);
            new RegExp(item.pattern, item.flags || '');
            if (typeof item.replacement !== 'string') throw new Error('Missing pattern translation');
            if (item.translateGroups && !item.translateGroups.every(n => Number.isInteger(n) && n > 0)) throw new Error('Invalid translated capture group');
            patterns.push(item);
        }
    }
}
const payload = {messages, patterns};
payload.version = crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex').slice(0, 12);
const generated = '// Hand-authored Simplified Chinese catalog. Generated by build.mjs.\nwindow.OCT_ZH_CN = ' + JSON.stringify(payload, null, 2).replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029') + ';\n';
const output = path.join(directory, 'zh-CN.js');
if (process.argv.includes('--check')) {
    if (fs.readFileSync(output, 'utf8') !== generated) throw new Error('Catalog changed; run node app-lib/i18n/build.mjs');
} else fs.writeFileSync(output, generated, 'utf8');
console.log(`Chinese catalog: ${Object.keys(messages).length} messages, ${patterns.length} patterns; version ${payload.version}`);
